export default function PostExcerptCard() {
  return (
    <article>
      <div>
        {Math.random() > 0.5 ? (
          <img className="mt-3 max-w-full" src="https://placehold.co/600x400" />
        ) : (
          ""
        )}
      </div>
      <h3 className="text-xl font-serif font-bold mt-3">Post Title</h3>
      <p className="italic text-slate-800 text-base">
        This is placeholder text for the post excerpt. The text could either be
        manually set on WordPress, or auto-generated by WordPress
      </p>
      <div className="text-slate-800 text-base mt-1">
        Simon Cossar <br />
        Feb 24, 2024
      </div>
    </article>
  );
}
